### PR TITLE
docs: added license file

### PR DESCRIPTION
**Pull request by UlisesGascon**
## Main changes

Updated license references to CC0 1.0 Universal, the same as we use for [onebeyond/awesome-systemic](https://raw.githubusercontent.com/onebeyond/awesome-systemic/main/LICENSE) (cc: @inigomarquinez ).

## Context

Related https://github.com/onebeyond/admin/issues/27

### CODE REVIEW

**Comment by inigomarquinez** [comment]
@UlisesGascon , is there a reason to use CCO instead of MIT for this repo?

**Review by inigomarquinez — COMMENTED** [review]
@UlisesGascon , is there a reason to use CCO instead of MIT for this repo?

**Comment by UlisesGascon** [comment]
As far as I understand from other projects such as [MDN](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license) or [Awesome], it is recommended to use CC0 for non-coding projects. In our case, this repository is purely documentation. However, we can look into it further to determine the best license for our non-coding repository.

**Comment by inigomarquinez** [comment]
> As far as I understand from other projects such as [MDN](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license) or [Awesome], it is recommended to use CC0 for non-coding projects. In our case, this repository is purely documentation. However, we can look into it further to determine the best license for our non-coding repository.

Ok, understood!

**Review by inigomarquinez — APPROVED** [review]

**Pull request merged**
